services:
    ctrl-plane:
        image: node:latest
        container_name: ctrl-plane
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - "50051:50051"
        networks:
            - app_network
        command: ["npx", "ts-node", "/app/server.ts"]
        depends_on:
            - database
        environment:
            - NODE_ENV=production
        stdin_open: true
        tty: true

    database:
        image: postgres:latest
        container_name: database
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5431:5432"
        networks:
            - app_network
    cache:
        image: redis:latest
        container_name: cache
        restart: always
        ports:
            - "6379:6379"
        networks:
            - app_network

networks:
    app_network:
