# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tjob.proto\x12\x03job\">\n\x10\x43reateJobRequest\x12\x13\n\x0bschedule_id\x18\x01 \x01(\x03\x12\x15\n\rscheduled_for\x18\x02 \x01(\t\"V\n\x07Payload\x12\x14\n\x0c\x63ommand_name\x18\x01 \x01(\t\x12\x16\n\x0e\x63ommand_script\x18\x02 \x01(\t\x12\x1d\n\x15\x63ommand_script_params\x18\x03 \x03(\t\"\xd0\x01\n\x0bJobResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x13\n\x0bschedule_id\x18\x02 \x01(\x03\x12\x1d\n\x07payload\x18\x03 \x01(\x0b\x32\x0c.job.Payload\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\x12\x0e\n\x06result\x18\x06 \x01(\t\x12\x15\n\rscheduled_for\x18\x07 \x01(\t\x12\x12\n\nstarted_at\x18\x08 \x01(\t\x12\x13\n\x0b\x66inished_at\x18\t \x01(\t\x12\x12\n\ncreated_at\x18\n \x01(\t\"\x1b\n\rGetJobRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"[\n\x0fListJobsRequest\x12\x18\n\x0bschedule_id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x13\n\x06status\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_schedule_idB\t\n\x07_status\"2\n\x10ListJobsResponse\x12\x1e\n\x04jobs\x18\x01 \x03(\x0b\x32\x10.job.JobResponse\"\xd2\x01\n\x10UpdateJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x03\x12\x13\n\x06status\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06result\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x17\n\nstarted_at\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0b\x66inished_at\x18\x06 \x01(\tH\x04\x88\x01\x01\x42\t\n\x07_statusB\x08\n\x06_errorB\t\n\x07_resultB\r\n\x0b_started_atB\x0e\n\x0c_finished_at2\xda\x01\n\x03Job\x12\x34\n\tCreateJob\x12\x15.job.CreateJobRequest\x1a\x10.job.JobResponse\x12.\n\x06GetJob\x12\x12.job.GetJobRequest\x1a\x10.job.JobResponse\x12\x37\n\x08ListJobs\x12\x14.job.ListJobsRequest\x1a\x15.job.ListJobsResponse\x12\x34\n\tUpdateJob\x12\x15.job.UpdateJobRequest\x1a\x10.job.JobResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEJOBREQUEST']._serialized_start=18
  _globals['_CREATEJOBREQUEST']._serialized_end=80
  _globals['_PAYLOAD']._serialized_start=82
  _globals['_PAYLOAD']._serialized_end=168
  _globals['_JOBRESPONSE']._serialized_start=171
  _globals['_JOBRESPONSE']._serialized_end=379
  _globals['_GETJOBREQUEST']._serialized_start=381
  _globals['_GETJOBREQUEST']._serialized_end=408
  _globals['_LISTJOBSREQUEST']._serialized_start=410
  _globals['_LISTJOBSREQUEST']._serialized_end=501
  _globals['_LISTJOBSRESPONSE']._serialized_start=503
  _globals['_LISTJOBSRESPONSE']._serialized_end=553
  _globals['_UPDATEJOBREQUEST']._serialized_start=556
  _globals['_UPDATEJOBREQUEST']._serialized_end=766
  _globals['_JOB']._serialized_start=769
  _globals['_JOB']._serialized_end=987
# @@protoc_insertion_point(module_scope)
