# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschedule.proto\x12\x08schedule\x1a\x1bgoogle/protobuf/empty.proto\"U\n\x10ScheduleResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x0c\x63ommand_name\x18\x02 \x01(\t\x12\x0f\n\x07\x63rontab\x18\x03 \x01(\t\x12\x0e\n\x06params\x18\x04 \x03(\t\"F\n\x15ListSchedulesResponse\x12-\n\tschedules\x18\x01 \x03(\x0b\x32\x1a.schedule.ScheduleResponse2T\n\x08Schedule\x12H\n\rListSchedules\x12\x16.google.protobuf.Empty\x1a\x1f.schedule.ListSchedulesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULERESPONSE']._serialized_start=57
  _globals['_SCHEDULERESPONSE']._serialized_end=142
  _globals['_LISTSCHEDULESRESPONSE']._serialized_start=144
  _globals['_LISTSCHEDULESRESPONSE']._serialized_end=214
  _globals['_SCHEDULE']._serialized_start=216
  _globals['_SCHEDULE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
